"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { LockKeyhole } from "lucide-react";
import Layout from "@/components/Layout";
import { login, register, saveAccessToken } from "@/lib/api";

export default function AuthPage() {
  const router = useRouter(); const [mode, setMode] = useState<"login" | "register">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [displayName, setDisplayName] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const switchMode = (nextMode: "login" | "register") => { setMode(nextMode); setPassword(""); setError(""); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const session = mode === "login" ? await login(email.trim(), password) : await register(email.trim(), password, displayName.trim()); saveAccessToken(session.access_token); router.push("/"); } catch (e) { setError(e instanceof Error ? e.message : "Authentication failed."); setBusy(false); } };
  return <Layout><div className="mx-auto max-w-md border-2 border-black bg-white p-6"><div className="flex items-center gap-3"><LockKeyhole className="h-8 w-8" aria-hidden="true" /><div><p className="font-mono text-[10px] font-black tracking-widest text-zinc-500">PRIVATE WARDROBE</p><h1 className="text-2xl font-black">{mode === "login" ? "Sign in" : "Create account"}</h1></div></div><p className="mt-4 text-sm text-zinc-600">Your account authorises access to your garments, personal images, and generated visualisations.</p><div className="mt-5 grid grid-cols-2 border-2 border-black p-1" aria-label="Authentication mode"><button type="button" onClick={() => switchMode("login")} aria-pressed={mode === "login"} className={`min-h-11 p-2 text-sm font-bold ${mode === "login" ? "bg-black text-white" : ""}`}>Sign in</button><button type="button" onClick={() => switchMode("register")} aria-pressed={mode === "register"} className={`min-h-11 p-2 text-sm font-bold ${mode === "register" ? "bg-black text-white" : ""}`}>Register</button></div>{error && <p role="alert" className="mt-4 border-2 border-rose-600 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<form onSubmit={submit} aria-busy={busy} className="mt-5 space-y-4">{mode === "register" && <label className="block text-sm font-bold">Display name<input required autoComplete="name" maxLength={100} disabled={busy} value={displayName} onChange={(event) => setDisplayName(event.target.value)} className="mt-1 min-h-11 w-full border-2 border-black p-2" /></label>}<label className="block text-sm font-bold">Email<input required type="email" inputMode="email" autoComplete="email" autoCapitalize="none" disabled={busy} value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 min-h-11 w-full border-2 border-black p-2" /></label><label className="block text-sm font-bold">Password<input required type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength={mode === "register" ? 12 : 1} disabled={busy} value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1 min-h-11 w-full border-2 border-black p-2" />{mode === "register" && <span className="mt-1 block text-xs font-normal text-zinc-500">Use at least 12 characters.</span>}</label><button type="submit" disabled={busy} className="min-h-11 w-full bg-black p-3 text-sm font-bold text-white disabled:opacity-40">{busy ? "Please wait…" : mode === "login" ? "Sign in" : "Create private account"}</button></form></div></Layout>;
}
